### ISSUE TITLE
Exception: Xcodeproj is not installed  even when XcodeProj is installed 

### ISSUE THREAD

**Issue by Kontrano** [AngeloAvv/flutter_flavorizr#250]
I tried to update a flavor today and got the error that Xcodeproj is not installed. This worked fine a few weeks ago. 

So I do the command gem install xcodeproj, It says its already installed. I also removed both versions I had and ran the command again but still, the same issue persists where Flavorizr is saying that I don't have it installed.

I get the following error in the console:

Executing task ios:xcconfig
Running XcodeprojProcessor: Checking if xcodeproj is installed
Unhandled exception:
Exception: Xcodeproj is not installed. Please install it by running `gem install xcodeproj`
#0      XcodeprojProcessor.execute (package:flutter_flavorizr/src/processors/darwin/xcodeproj_processor.dart:20:7)
#1      QueueProcessor.execute (package:flutter_flavorizr/src/processors/commons/queue_processor.dart:44:17)
#2      Processor.execute (package:flutter_flavorizr/src/processors/processor.dart:140:24)
<asynchronous suspension>

Any idea what could be happening? I also updated Ruby Gems and xcodeproj to the latest version but no change.

**Comment by EvertonMJunior** [comment]
Same error here. Error when running even though xcodeproj is installed.
![image](https://github.com/AngeloAvv/flutter_flavorizr/assets/51867881/95e76c92-388b-4289-af75-1006324c8c63)

**Comment by AngeloAvv** [comment]
Can you please provide the output of:

`gem list -i ^xcodeproj$`

and

`gem list xcodeproj`

**Comment by anas43950** [comment]
The output for first command is true
And for second command: xcodeproj (1.24.0)

**Comment by anas43950** [comment]
![image](https://github.com/user-attachments/assets/fb77e398-a82e-4406-8886-47b2fcc2a306)
Everything is installed as you can see, still throwing error

**Comment by yousefak007** [comment]
same problem

**Comment by yousefak007** [comment]
Hi,

You must add a `.cmd` extension for `gem` in `xcodeproj_processor.dart`.
you can find it in `Pub\Cache\hosted\pub.dev\flutter_flavorizr-[VERSION]\lib\src\processors\darwin\xcodeproj_processor.dart`
 

![image](https://github.com/user-attachments/assets/02adbce8-f814-4ea0-9df5-e224fa88dfc7)

**Comment by Kontrano** [comment]
> Hi, for temp solution:
> 
> You must add a `.cmd` extension for `gem` in `xcodeproj_processor.dart`. you can find it in `Pub\Cache\hosted\pub.dev\flutter_flavorizr-[VERSION]\lib\src\processors\darwin\xcodeproj_processor.dart`
> 
> ![image](https://private-user-images.githubusercontent.com/46021584/352552669-02adbce8-f814-4ea0-9df5-e224fa88dfc7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY1NTk4MzQsIm5iZiI6MTcyNjU1OTUzNCwicGF0aCI6Ii80NjAyMTU4NC8zNTI1NTI2NjktMDJhZGJjZTgtZjgxNC00ZWEwLTlkZjUtZTIyNGZhODhkZmM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE3VDA3NTIxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE3NTY3MDdjM2MzNjIxNTE2YjRiMDU1MTc3ODUzOGNhYzc4NTdlYTAyYmM4NWZkNWYzNWRmNDIyYmZjMDYyMDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XkkD5LmzHG4DUbg7ubqAN84sigF_i2WeMQM31doryJ4)
> 
> cc: @AngeloAvv

This still seems to be the only thing that works

**Comment by AngeloAvv** [comment]
> > Hi, for temp solution:
> > You must add a `.cmd` extension for `gem` in `xcodeproj_processor.dart`. you can find it in `Pub\Cache\hosted\pub.dev\flutter_flavorizr-[VERSION]\lib\src\processors\darwin\xcodeproj_processor.dart`
> > ![image](https://private-user-images.githubusercontent.com/46021584/352552669-02adbce8-f814-4ea0-9df5-e224fa88dfc7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY1NTk4MzQsIm5iZiI6MTcyNjU1OTUzNCwicGF0aCI6Ii80NjAyMTU4NC8zNTI1NTI2NjktMDJhZGJjZTgtZjgxNC00ZWEwLTlkZjUtZTIyNGZhODhkZmM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE3VDA3NTIxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE3NTY3MDdjM2MzNjIxNTE2YjRiMDU1MTc3ODUzOGNhYzc4NTdlYTAyYmM4NWZkNWYzNWRmNDIyYmZjMDYyMDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XkkD5LmzHG4DUbg7ubqAN84sigF_i2WeMQM31doryJ4)
> > cc: @AngeloAvv
> 
> This still seems to be the only thing that works

It doesn't work for me, it says command not found: gem.cmd, so it's not a good solution that would work for everyone

**Comment by Kontrano** [comment]
> > > Hi, for temp solution:
> > > You must add a `.cmd` extension for `gem` in `xcodeproj_processor.dart`. you can find it in `Pub\Cache\hosted\pub.dev\flutter_flavorizr-[VERSION]\lib\src\processors\darwin\xcodeproj_processor.dart`
> > > ![image](https://private-user-images.githubusercontent.com/46021584/352552669-02adbce8-f814-4ea0-9df5-e224fa88dfc7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY1NTk4MzQsIm5iZiI6MTcyNjU1OTUzNCwicGF0aCI6Ii80NjAyMTU4NC8zNTI1NTI2NjktMDJhZGJjZTgtZjgxNC00ZWEwLTlkZjUtZTIyNGZhODhkZmM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE3VDA3NTIxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE3NTY3MDdjM2MzNjIxNTE2YjRiMDU1MTc3ODUzOGNhYzc4NTdlYTAyYmM4NWZkNWYzNWRmNDIyYmZjMDYyMDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XkkD5LmzHG4DUbg7ubqAN84sigF_i2WeMQM31doryJ4)
> > > cc: @AngeloAvv
> > 
> > 
> > This still seems to be the only thing that works
> 
> It doesn't work for me, it says command not found: gem.cmd, so it's not a good solution that would work for everyone
> 
> Question: .cmd files are used on Windows, are you running flutter_flavorizr on Windows? If you have iOS/macOS flavors, you must run flutter_flavorizr on macOS. There's no way you could use xcodeproj gem on other operating systems

I am indeed running on windows, and its actually always worked perfectly on windows, no need to be on macOS to create flavors, which is also the thing i love so much about this package. This issue that i needs to be set to .cmd has only happened the last 6 months or so before that i never had an issue

**Comment by AngeloAvv** [comment]
Ok, now I see the bigger picture caused by the introduction of more restricted checks on xcodeproj. 

A lot of people do not read the README and forget about installing the gem, therefore they keep opening the same issue repeatedly, that's why I introduced this kind of check. 

I honestly never ran flutter_flavorizr on other OSes than macOS when I needed to flavorize iOS/macOS apps, that's why I'm saying it will never work (I mean, it could, but I never tested it)

At this point, at least I know how to reproduce this issue. Let me think about it and I will come back with a solution

**Comment by Kontrano** [comment]
No worries, very understandable! But great that where the issue lies is now clear, if you need any additional info from me let me know!

**Comment by suhailthajudeen** [comment]
Same issue am also facing
<img width="1061" alt="image" src="https://github.com/user-attachments/assets/09ffb9a3-73ec-40c7-ae7e-4261255896c2">

**Comment by Mr-yuwei** [comment]
need help

**Comment by Kontrano** [comment]
@Mr-yuwei @suhailthajudeen see the fix/workaround above

**Comment by lcsvcn** [comment]
no definitive solution still?

**Comment by AngeloAvv** [comment]
Unfortunately, I still haven't had the time to work on this. I'll try to take a look in the next weeks

**Comment by AngeloAvv** [comment]
Hey @Kontrano , I opened a [PR](https://github.com/AngeloAvv/flutter_flavorizr/pull/295) that should fix the aforementioned problem. I was about to test and merge it but then I read about [this](https://github.com/AngeloAvv/flutter_flavorizr/issues/289).

In this conversation, you said the problem should be fixed by appending the .cmd extension while running the ShellProcessor, on the other hand, @micheljung has a binary with a .bat extension instead.

I'm assuming Ruby is shipping different files when distributing different versions of itself. I want to move this ticket forward, and I want to find a way to solve the problem once and for all and make everybody happy. Can we find a way to meet us halfway?
