### ISSUE TITLE
Unable to load flavor after hot restart on Flutter 3.32.x and beyond

### ISSUE THREAD

**Issue by mafreud** [AngeloAvv/flutter_flavorizr#256]
I set up a flavor/custom scheme using ```flutter_flavorizr```. 

Everything works great, but after hot restarting, the app does not load flavor.

Any solutions?

Regards

**Comment by AngeloAvv** [comment]
Hey @mafreud , I think it might related to your specific Flutter project because I can't find a way to reproduce it. Can you please provide a sample project or more info to help me investigate the issue?

**Comment by mafreud** [comment]
@AngeloAvv 
Thank you for the comment. I think it has been solved.

**Comment by RedC4ke** [comment]
Hi, how did you solve it? I'm getting a similar issue

**Comment by AngeloAvv** [comment]
> Me too, just with a simple code [@AngeloAvv](https://github.com/AngeloAvv)
> 
> void main() async { print("MY FLAVOR FLAVOR $appFlavor"); F.appFlavor = Flavor.values.firstWhere((element) => element.name == appFlavor); }
> 
> first time when starts i got my flavor in appFlavor, but when i do hot reload it returns null
> 
> I/flutter (11385): MY FLAVOR FLAVOR marcus
> 
> Performing hot restart... Restarted application in 672ms. I/flutter (11385): MY FLAVOR FLAVOR null E/flutter (11385): [ERROR:flutter/runtime/dart_vm_initializer.cc(40)] Unhandled Exception: Bad state: No element E/flutter (11385): #0 ListBase.firstWhere (dart:collection/list.dart:132:5) E/flutter (11385): [#1](https://github.com/AngeloAvv/flutter_flavorizr/issues/1) main (package:barber_shop/main.dart:16:31) E/flutter (11385): [#2](https://github.com/AngeloAvv/flutter_flavorizr/issues/2) _runMain. (dart:ui/hooks.dart:320:23) E/flutter (11385): [#3](https://github.com/AngeloAvv/flutter_flavorizr/pull/3) _delayEntrypointInvocation. (dart:isolate-patch/isolate_patch.dart:314:19) E/flutter (11385): [#4](https://github.com/AngeloAvv/flutter_flavorizr/issues/4) _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:193:12) E/flutter (11385):

How are you launching your Flutter app, and what platform are you targeting?

**Comment by brasizza** [comment]
> > Me too, just with a simple code [@AngeloAvv](https://github.com/AngeloAvv)
> > void main() async { print("MY FLAVOR FLAVOR $appFlavor"); F.appFlavor = Flavor.values.firstWhere((element) => element.name == appFlavor); }
> > first time when starts i got my flavor in appFlavor, but when i do hot reload it returns null
> > I/flutter (11385): MY FLAVOR FLAVOR marcus
> > Performing hot restart... Restarted application in 672ms. I/flutter (11385): MY FLAVOR FLAVOR null E/flutter (11385): [ERROR:flutter/runtime/dart_vm_initializer.cc(40)] Unhandled Exception: Bad state: No element E/flutter (11385): #0 ListBase.firstWhere (dart:collection/list.dart:132:5) E/flutter (11385): [#1](https://github.com/AngeloAvv/flutter_flavorizr/issues/1) main (package:barber_shop/main.dart:16:31) E/flutter (11385): [#2](https://github.com/AngeloAvv/flutter_flavorizr/issues/2) _runMain. (dart:ui/hooks.dart:320:23) E/flutter (11385): [#3](https://github.com/AngeloAvv/flutter_flavorizr/pull/3) _delayEntrypointInvocation. (dart:isolate-patch/isolate_patch.dart:314:19) E/flutter (11385): [#4](https://github.com/AngeloAvv/flutter_flavorizr/issues/4) _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:193:12) E/flutter (11385):
> 
> How are you launching your Flutter app, and what platform are you targeting?

even with **flutter run --flavor=marcus**  when i do a hot restart the error happens,
digging, i realize that appFlavor don't get the expected value when do a hot restart, and then i changed my code to create one main_x.dart for each flavo and set the flavor manually

```dart
void main() async {
  F.appFlavor = Flavor.marcus;
  runApp(const App());
}```

I am using 
```
Flutter 3.32.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision be698c48a6 (8 days ago) • 2025-05-19 12:59:14 -0700
Engine • revision 1881800949 (8 days ago) • 2025-05-19 10:54:07 -0700
Tools • Dart 3.8.0 • DevTools 2.45.1```
